### PR TITLE
feat: add source into provider.tf

### PR DESCRIPTION
**Pull request by Yu-Jack**
## Problem

According to https://github.com/harvester/harvester/issues/4859#issue-2036948026, before you run `terraform init`, **you should execute following two steps**.

1. Run `terraform state replace-provider -auto-approve "registry.terraform.io/-/harvester" "harvester/harvester"`
2. Add `source = "harvester/harvester"` in `generated/harvester/image/provider.tf` like below.
```diff
terraform {
	required_providers {
		harvester = {
+			source = "harvester/harvester"
			version = "~> 0.6.3"
		}
	}
}
```

## Solution

About second step, I find out the [GoogleCloudPlatform/terraformer](https://github.com/GoogleCloudPlatform/terraformer/blob/master/terraformutils/terraformoutput/hcl.go#L36-L38), [PR](https://github.com/GoogleCloudPlatform/terraformer/pull/1488/files#diff-cbac0650204e1e60f5af60ae78912c11364b91323e2ca607fcfa637049d0bb85) already added this feature. So, I sync those codes into our harvester/terraformer. Next time, we don't need to remember to execute second step.

## Related Issue

https://github.com/harvester/harvester/issues/4859

### Prepare the provider

1. mkdir -p ~/.terraform.d/plugins/linux_amd64
2. wget https://github.com/harvester/terraform-provider-harvester/releases/download/v0.6.4/terraform-provider-harvester_0.6.4_linux_amd64.zip
3. unzip terraform-provider-harvester_0.6.4_linux_amd64.zip
4. mv terraform-provider-harvester_v0.6.4 ~/.terraform.d/plugins/linux_amd64

### Start to test

1. Prepare a harvester cluster with uploaded image.
2. Use `go build` to build executable binary in this project home path.
3. Run `./terraformer import harvester -r image` after you make sure your `KUBECONFIG` point to harvester.
4. Run `cd generated/harvester/image/`
5. Run `terraform state replace-provider -auto-approve "registry.terraform.io/-/harvester" "harvester/harvester"` which [GoogleCloudPlatform/terraformer mentioned](https://github.com/GoogleCloudPlatform/terraformer?tab=readme-ov-file#migration-state-version)
6. Run `terraform init`

And I tested following terrform version
  - 1.6.5
  - 1.5.0
  - 0.13.7

### CODE REVIEW

**Comment by FrankYang0529** [comment]
Hi @Yu-Jack, since our repo is forked from https://github.com/GoogleCloudPlatform/terraformer.  Do you think it's worth to rebased to upstream master branch, so we can have fixes/features from upstream?

**Comment by Yu-Jack** [comment]
@FrankYang0529 I think it makes sense, but the Golang is 1.21 in upstream/master, does it have possible to affect our existing flow or project if we rebase it?

**Comment by Yu-Jack** [comment]
Actually, I think we could put off rebasing until our harvester 1.3 is GA. Because honestbee/jobq not found error is quite annoying, especially rebasing upstream/master causes a lots of go.mod changes, so I'm thinking we could do it later? Do you have any thought about this?

By the way, I have another question about why don't we merge our harvester code into upstream? Just curious.

**Comment by Yu-Jack** [comment]
I think we could schedule another issue to do rebasing if we think rebasing is worth to do. 

By the way, I have a question about why don't we merge our harvester code into upstream like the other providers do? Just curious. I know we could easily manage our terraformer after we fork. But, there is also a same problem for syncing new fix/features from upstream. That means we need to do rebasing periodically.

**Comment by FrankYang0529** [comment]
> I think we could schedule another issue to do rebasing if we think rebasing is worth to do.

After checking upstream change, I think most of change is about other providers. We can postpone it currently.

> By the way, I have a question about why don't we merge our harvester code into upstream like the other providers do?

Actually, I'm not sure, but we can check how to add our plugin to upstream in the future. Also, need to check whether it's easier to update it.

**Review by FrankYang0529 — APPROVED** [review]
LGTM. It's good to add another setup steps:

If you has error like `2023/12/26 16:05:27 open /home/poanyang/.terraform.d/plugins/linux_amd64: no such file or directory`, you can do following steps to fix it:

1. mkdir -p /home/poanyang/.terraform.d/plugins/linux_amd64
2. wget https://github.com/harvester/terraform-provider-harvester/releases/download/v0.6.4/terraform-provider-harvester_0.6.4_linux_amd64.zip
3. unzip terraform-provider-harvester_0.6.4_linux_amd64.zip
4. mv terraform-provider-harvester_v0.6.4 ~/.terraform.d/plugins/linux_amd64

**Comment by Yu-Jack** [comment]
> After checking upstream change, I think most of change is about other providers. We can postpone it currently.

I agree with that. I also checked the upstream/master commit yesterday, it's related to new providers mostly. Besides, it seems the [terraformutils](https://github.com/GoogleCloudPlatform/terraformer/tree/master/terraformutils) is not update frequently. I think it's not too hard to merge feat/fix which is related the terraformer self into our terraformer if we don't choose rebasing. Anyway, It could depend what we need.

**Review by bk201 — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
